


localhost:8080
	MAX_CLIENT_MESSAGE_SIZE=10G
	ERROR_PAGES=404|/errors/404.html
	403|/test_dir/403.html
	ROUTES=111|/shit|/route|.|0|.|1110#comments
	110|/|/|.|1|.|1111
	/oldurl/smshit|/home.html
	/another|/oui

