10.13.7.8:8080
	MAX_CLIENT_MESSAGE_SIZE=10G
	ERROR_PAGES=404|/errors/404.html
	ROUTES=111|/test_dir|/route|/test_dir/pics|0|logfile.txt|1110#comments
	110|test_dir|/|/test_dir/pics|1|logfile.txt|1111
	/oldurl/smshit|/home.html
	/another|/oui

