localhost:8080
	MAX_CLIENT_MESSAGE_SIZE=10G# 20 bytes
	ERROR_PAGES=404|/errors/404.html
	ROUTES=111|/test_dir|/route|/test_dir/pics|0|errors/404.html|1110#comments
	111|/test_dir|/|./test_dir/pics|1|errors/404.html|1111
	/|/home.html
	/another|/oui

